//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace net_quiz_sample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Problems
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public string Category { get; set; }
        public byte Difficulty { get; set; }
        public string Options { get; set; }
        public byte Answer { get; set; }
    }
}
